### PR TITLE
[Header & Footer] Header & Footer Documentation

### PR DESCRIPTION
**Pull request by burgwyn**
## Description

Documentation of header and footer in SAMUIKit

### CODE REVIEW

**Comment by joshbruce** [comment]
@burgwyn and @eoladipo - Sorry for breaking this merge. :/

We recently changed the folder structure within `/includes` and changed the website build a bit. If you rebase - delete everything within `/assets` - and serve the site again and update the PR, it should be okay.

I will most likely come back today and comment on some of the things I'm seeing - working on the SAMWDS release right now.

We are also looking to try to get the SAMWDS site hosted elsewhere to minimize conflicts caused by this type of thing. Referencing #83 to demonstrate issues that can occur by not implementing the recommendation found there.

**Comment by eoladipo** [comment]
@joshbruce @burgwyn 

The documentation aside from the main header is comprised of screen shots. The description needs to be added but need clarity on what it should be.

Thanks,

Ebun

**Comment by eoladipo** [comment]
@joshbruce I will work on redoing the pull request based on your comments, thanks.

**Comment by eoladipo** [comment]
@joshbruce A new PR has been created in place of this one so this do to the conflicts. https://github.com/GSA/sam-web-design-standards/pull/117

**Comment by eoladipo** [comment]
@joshbruce I'm following up with you per this pull request, did you get a chance to review it yet? 
@burgwyn

**Comment by joshbruce** [comment]
@eoladipo - Sorry, been a crazy week. When I get a chance, most likely tomorrow, I will do the merge. I have put in my plan for this Sprint to do the refactor/re-engineering piece. So much has been happening I feel like we (the core team) dropped the ball a bit with y'all. I'm going to be sending out an email tomorrow to the Scrum Masters to reiterate some of the things that were discussed today.

**Comment by eoladipo** [comment]
@joshbruce @burgwyn Thanks for the update.

**Comment by joshbruce** [comment]
Closing

**Pull request closed without merging**
