### PR TITLE
[WIP][Website] Adding micro-site section

### PR DESCRIPTION
**Pull request by carlosvalle**
## Description

see #80 

## Additional information

Everything in the list its done except
- [ ] Create /_templates/microsite-base.html to use a the base/default page template.

@joshbruce - Not sure what needs to be included in the templates section (I'm using the default page template) Did you mean create a _layout page for microsite?

### CODE REVIEW

**Comment by joshbruce** [comment]
@carlosvalle - Sweet!

Yep; so, the Jekyll front-matter might look something like this:

```
---
permalink: /micro-site/
layout: microsite
title: SAM.gov micro-site home
---
```

The microsite.html file - would pull in, or contain the html for the approved header and footer - instead of the style guide header and footer. I'm pretty sure Liquid is similar enough to other template engines that it can do this...based on the styleguide.html.

I would like to try something, if you're game? 

I want to open this PR locally - and see if I can contribute directly to this PR - straight GitHub experiment. But, I don't want to do it without your go ahead.

(I think we're starting a conversation about granting write access, and what that would look like, testing pros and cons.)

But, it's Friday - have a great weekend! We can talk more Monday.

**Comment by carlosvalle** [comment]
go ahead @joshbruce

**Comment by joshbruce** [comment]
@carlosvalle - It is *not* possible for  the non-owner of the PR to update it. Both good an bad there.

I think this gives us a good base to work - do you want to tag me in (me to merge and submit another)? Or, I could hop over to your fork and start submitting PRs against the branch there?

Let me know.

**Comment by carlosvalle** [comment]
@joshbruce - We might need to collaborate in the future so I added you as collaborator to my fork  +1 on having that conversion with the team to define collaboration workflow

**Comment by joshbruce** [comment]
@carlosvalle - Sounds good. Heading over there now. I will try to put together an issue for this discussion - we have tried a couple of different ways of doing this (will catalog them there). Going to be trying another one for this time.

**Comment by joshbruce** [comment]
@carlosvalle - Can you verify you added me as a collaborator on https://github.com/carlosvalle/sam-web-design-standards - if you marked me as a "read" could you mark me as "write" - promise to not blow anything up?

**Comment by joshbruce** [comment]
@carlosvalle - Scratch that last - had to accept the invitation.

**Pull request merged**
