### PR TITLE
[Website] Search results example page

### PR DESCRIPTION
**Pull request by carlosvalle**
## Description

* Adding example search results page 

## Additional information

* starting version for the search results page, lets discuss and see whats needed to improve it

### CODE REVIEW

**Comment by joshbruce** [comment]
@carlosvalle - This is pretty awesome!

This makes me think we should consider a "micro-site" type approach. Creating a "base" template with the HTML from the header and footer, and use *that* template with ideas like this. Of course, the base template for use in the micro-site should include a message about not being live data, a live site, and have a link back to the Standards themselves.

Also, thinking it would be worthwhile to put the search results for the various object (data) types to give us a way to see what content and metadata should be while also being able to see each variation on one screen.

I believe @tarandhupar and @jagannathch also have a feature this sprint to discuss page templates and whatnot, might be worth discussing/showing them.

Tagging in @ChristyHermansen and @BrianGilmanGSA as well.

**Comment by joshbruce** [comment]
@carlosvalle - See #80 and #81 

If you would rather take the reins - since you inspired the idea - please let me know. I have something else I need to work on for the next couple of hours. I could easily merge in this PR to `gh-pages-staging` and keep the good work here.

Going to tag in: @anuragmundada-reisys and @diego-ruiz-rei as well.

**Comment by carlosvalle** [comment]
@joshbruce - sure, I'll work on this

**Comment by joshbruce** [comment]
@carlosvalle - Cool, thanks! I will let the rest of the team know.

What's the timing look like on your end? I might be able to take on parts as well.

**Comment by carlosvalle** [comment]
@joshbruce - I just have to finish a couple things first but I'll be done in about two hours - after that I can work on this

**Pull request closed without merging**
