### PR TITLE
[Website] Fix styleguide.scss not showing changes

### PR DESCRIPTION
**Pull request by carlosvalle**
### Steps to reproduce issue
* run `gulp website:serve`
* Add/modify a style in  `_site-assets/css/styleguide.scss` 
* gulp watch will detect the change but the styles will not show on the docs page

## Additional information

* This pull request fixes this issue and remove files that are not necessary

### CODE REVIEW

**Comment by joshbruce** [comment]
@carlosvalle - Think this is a great idea, and there might be limitations (#12). 

We are using a standard GitHub pages Jekyll build and I ran into issues when trying to get the GitHub Pages Jekyll build to use the `_config.yml`.

What do you think of me doing a merge - then merging into gh-pages to verify GitHub will still accurately build the site? 

I don't think it will be difficult to revert.

**Comment by CarlosValle-REISys** [comment]
@joshbruce - thats a good idea, lets do a merge and test

**Comment by carlosvalle** [comment]
@joshbruce - thats a good idea, lets do a merge and test

**Comment by joshbruce** [comment]
@carlosvalle - Looks like the build worked (includes are updated):

https://gsa.github.io/sam-web-design-standards/

screen shot 2016-08-15 at 12 39 10 pm

Just not finding the assets...??

There are two source folders, technically:

1. `/src/stylesheets/all` - this establishes the CSS for the package
2. `_site_assets/css/styleguide.scss` - this extends the base with styles specific to the site itself.

Then, at least the rapid theory was, to have all that compile into:

`/assets` - this, I believe, is the folder the default GitHub Jekyll build copies and puts in `_site`.

Think the `/assets` folder still contains things it doesn't need necessarily.

Thoughts?

**Comment by joshbruce** [comment]
@carlosvalle - One way to check if the build works with gh-pages is to go to the site on your local account: [github username].github.io/sam-web-design-standards

You would need to push changes into your gh-pages branch. Note: This may cause you to have to rebase against the origin to avoid merge conflicts in the future since you would be updating into a branch that is normally reserved for pulls from origin.

**Pull request merged**
